"""Build the approved Version 5 pages with the targeted Version 6 guidelines conversion."""
from pathlib import Path
from html import escape as e
import json
import re
from guidelines_document import build_guidelines

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist'
REV = 'v5-20260907'
assets = {int(''.join(filter(str.isdigit,r['source']))):r for r in json.loads((ROOT/'docs/asset-map.json').read_text())}
assets.update({r['key']:r for r in json.loads((ROOT/'docs/asset-map-v4.json').read_text())})
assets.update({r['key']:r for r in json.loads((ROOT/'docs/asset-map-v5.json').read_text())})

def scientific_text(text):
    return re.sub(r'\b(Sclerotinia sclerotiorum|Cercospora|Fusarium)\b', r'<i>\1</i>', e(text))

def photo(n, alt, cls='', eager=False):
    r=assets[n]; w,h=r['size']
    return f'<img src="{r["asset"]}" width="{w}" height="{h}" alt="{e(alt)}" class="{cls}" loading="{"eager" if eager else "lazy"}" decoding="async">'

def figure(n, alt, caption='', cls=''):
    r=assets[n]
    label='' if caption is None else f'<figcaption>{scientific_text(caption or alt)} <span aria-hidden="true">↗</span></figcaption>'
    return f'<figure class="scientific-figure {cls}"><a href="{r["asset"]}" target="_blank" rel="noopener" aria-label="Open full-size image: {e(alt)}">{photo(n,alt)}</a>{label}</figure>'

menus = [
 ('Research',[('All research themes','research.html'),('NLR Regulation in Plants','research.html#nlr-temperature'),('Soybean Host–Pathosystem','research.html#soybean-loci'),('Soil Microbiome and BioProducts','research.html#soil-microbial-genomics')]),
 ('Our Approach',[('Lab-to-Land Approach','index.html#approach'),('Genome Sequencing','index.html#genome-sequencing'),('Spatial Transcriptomics','index.html#spatial-transcriptomics'),('Genetic Engineering','index.html#genetic-engineering'),('Stakeholder Input','index.html#stakeholder-input'),('Institutional / Collaborative Integration','index.html#collaborative-integration')]),
 ('About the Team',[('Meet the team','team.html'),('Principal Investigator','team.html#principal-investigator'),('Graduate Students','team.html#graduate-students'),('Undergraduate Students','team.html#undergraduate-students'),('Temporary Staff','team.html#temporary-staff'),('Lab Alumni','team.html#lab-alumni')]),
 ('Outreach',[('Outreach and engagement','outreach.html'),('GeN-G & GeN-G BRING','outreach.html#gen-ng'),('Field Contact','outreach.html#field-contact'),('Industry Partnerships','outreach.html#industry')]),
 ('Funding',[('Research support','funding.html'),('Federal Programs','funding.html#federal'),('Commodity Groups','funding.html#commodity')])
]

def header(active=''):
    items=''
    for title,links in menus:
        on=' current' if title==active else ''
        items+=f'<details class="nav-dropdown{on}"><summary>{title}<span class="chevron" aria-hidden="true"></span></summary><div class="dropdown-panel">'+''.join(f'<a href="{href}">{name}</a>' for name,href in links)+'</div></details>'
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html" aria-label="Solanki Lab home"><img src="assets/brand/solanki-lab.png" width="70" height="70" alt=""><span>SOLANKI <b>LAB</b></span></a><button class="nav-toggle" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">{items}<a class="nav-direct {'current' if active=='Recruitment' else ''}" href="recruitment.html">Recruitment</a><a class="nav-direct {'current' if active=='Lab Guidelines' else ''}" href="guidelines.html">Lab Guidelines</a></nav></header>'''

footer='''<footer class="site-footer"><div><a class="footer-brand" href="index.html">SOLANKI LAB</a><p>Functional Genomics · Plant–Microbe–Soil Interactions</p></div><div><a href="mailto:shyam.solanki@sdstate.edu">shyam.solanki@sdstate.edu</a><address class="contact-address"><strong>Shyam Solanki, PhD</strong><br>Assistant Professor<br>Functional Genomics of Plant Microbe Soil Interaction<br>Agronomy, Horticulture, &amp; Plant Science<br>South Dakota State University<br>Berg Agricultural Hall 251, Box 2100A<br>Brookings, SD 57007<br><a href="tel:+16056885032">(605) 688-5032</a></address></div><div class="footer-links"><a href="team.html">Our team</a><a href="guidelines.html">Lab guidelines</a><a href="research.html">Research</a></div></footer>'''

def page(name,title,description,body,active='',home=False,extra_head=''):
    backdrop='<canvas id="universe" aria-hidden="true"></canvas><div class="shade" aria-hidden="true"></div>' if home else '<div class="quiet-backdrop" aria-hidden="true"></div>'
    scripts=f'<script src="site.js?{REV}" defer></script>'+(f'<script src="universe.js?{REV}" defer></script>' if home else '')
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#03070b"><title>{e(title)} | Solanki Lab</title><meta name="description" content="{e(description)}"><link rel="icon" type="image/png" href="assets/brand/favicon.png"><link rel="stylesheet" href="style.css?{REV}">{extra_head}</head><body class="{'home-page' if home else 'secondary-page'}">{backdrop}{header(active)}<main id="main">{body}</main>{footer}{scripts}</body></html>'''
    (OUT/name).write_text(html)

def intro(kicker,title,text):
    return f'<section class="page-intro wrap"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="page-lead">{text}</p></section>'

themes=[
 ('Plant Immunity','Investigating the molecular mechanisms that shape how plants recognize and respond to pathogens.','nlr-temperature','IMMUNITY'),
 ('Microbial Solutions','Discovering soil microbial communities and beneficial microorganisms that support plant health, disease suppression, and crop resilience.','biostimulants','MICROBIOME'),
 ('Functional Genomics','Connecting genes, expression, and biological function to understand complex plant–microbe–soil relationships.','spatial-regulation','GENOMICS'),
 ('AI–Protein Modeling','AI-guided modeling and design of NLR immune receptor function for temperature adaptation and disease resistance.','nlr-temperature','PROTEIN DESIGN'),
 ('Resilient Crops','Bringing molecular insight into disease resistance to develop practical crop health solutions.','soybean-loci','CROP HEALTH')
]
cards=''.join(f'<a class="orbit-card" href="research.html#{anchor}"><span class="card-index">0{i+1} / {tag}</span><h3>{title}</h3><p>{text}</p><span class="card-link">Explore the theme <span aria-hidden="true">↗</span></span></a>' for i,(title,text,anchor,tag) in enumerate(themes))
steps=[
 ('genome-sequencing','Genome Sequencing','Read the biological blueprint.','Sequence plant, pathogen, and microbial genomes to characterize diversity and identify candidate genes and biological functions.'),
 ('spatial-transcriptomics','Spatial Transcriptomics','Locate the response.','Connect gene expression with tissue structure to understand where and when resistance responses unfold.'),
 ('genetic-engineering','Genetic Engineering','Test the mechanism.','Use molecular tools to test gene function and evaluate approaches to plant immunity and microbial crop protection.'),
 ('stakeholder-input','Stakeholder Input','Start with field priorities.','Work with farmers and industry partners to connect research questions with disease pressure, crop health, and production needs.'),
 ('collaborative-integration','Institutional / Collaborative Integration','Bring the expertise together.','Combine expertise across institutions and disciplines to connect molecular discovery, validation, formulation, and agricultural application.')
]
stephtml=''.join(f'<article class="approach-step" id="{anchor}"><span class="step-number">0{i+1}</span><div><h3>{title}</h3><p class="step-prompt">{short}</p><p>{text}</p></div></article>' for i,(anchor,title,short,text) in enumerate(steps))
home=f'''<section class="hero"><p class="eyebrow">FUNCTIONAL GENOMICS · PLANT–MICROBE–SOIL INTERACTIONS</p><h1>From molecules to living systems:<br><em>Discovery rooted in biology.</em></h1><p class="intro">The Solanki Lab is based in the Department of Agronomy, Horticulture and Plant Science at South Dakota State University. Our research integrates multiple approaches to explore how plants, microbes, and soil interact—and how understanding these relationships can help us develop more resilient crops.</p><a class="primary" href="#research">Explore our research <span aria-hidden="true">↗</span></a><div class="hero-bottom"><button id="motion" aria-pressed="false">Pause motion <span aria-hidden="true">Ⅱ</span></button></div></section>
<section id="research" class="content research-home"><div class="section-heading"><div><p class="eyebrow">01 / RESEARCH</p><h2>Small interactions.<br>Far-reaching questions.</h2></div></div><div class="orbit-stage" aria-label="Five research themes"><div class="orbit-ring" aria-hidden="true"></div><div class="orbit-core" aria-hidden="true"><img src="assets/brand/solanki-lab.png" alt="" width="150" height="150"><span>FG–PMSI</span></div>{cards}</div><div class="section-end"><a class="text-link" href="research.html">All research themes <span aria-hidden="true">↗</span></a></div></section>
<section id="approach" class="content approach"><div class="section-heading"><div><p class="eyebrow">02 / OUR APPROACH</p><h2>Lab-to-Land Approach</h2></div><p class="section-lead">Molecular discovery, guided by the needs of agriculture.</p></div><div class="approach-list">{stephtml}</div><p class="scientific-narrative">Functional Genomics <span>→</span> Plant–Microbe–Soil Interactions <span>→</span> Molecular Discovery <span>→</span> Translation <span>→</span> Crop Resilience</p></section>
<section id="about" class="content team-preview"><div><p class="eyebrow">03 / ABOUT THE TEAM</p><h2>Team-enabled science</h2><p>Our laboratory brings together people working across molecular biology, genomics, imaging, computational analysis, and field research.</p><a class="primary" href="team.html">Meet the team <span aria-hidden="true">↗</span></a></div><div class="team-preview-photos"><a class="team-preview-photo" href="team.html" aria-label="Meet the Solanki Lab team">{photo('group-lab','Solanki Lab group together in the laboratory')}</a><a class="team-preview-photo" href="team.html" aria-label="Meet the Solanki Lab team">{photo('group-team','Solanki Lab group together in a meeting room')}</a></div></section>
<section class="content outreach-preview"><div><p class="eyebrow">04 / OUTREACH</p><h2>Science in the community.</h2><p>Hands-on genomics education, conversations in the field, and local industry partnerships connect our laboratory with the people it serves.</p></div><div class="outreach-links"><a href="outreach.html#gen-ng">GeN-G &amp; GeN-G BRING <span>Genomics for the next generation ↗</span></a><a href="outreach.html#field-contact">Field Contact <span>Across South Dakota ↗</span></a><a href="outreach.html#industry">Industry Partnerships <span>Solutions shaped by farmer needs ↗</span></a></div></section>'''
page('index.html','Functional Genomics & Plant–Microbe–Soil Interactions','Solanki Lab at South Dakota State University explores functional genomics and plant–microbe–soil interactions, from molecular discovery to crop resilience.',home,home=True)

programs=[
 {'id':'soybean-loci','title':'Soybean Disease Resistance Loci','tag':'SOYBEAN HOST–PATHOSYSTEM','color':'mint','text':'We investigate the genetic basis of soybean disease resistance by connecting variation across soybean germplasm with disease phenotypes. Soilborne diseases such as white mold and Fusarium diseases are a primary focus, while Cercospora and other foliar diseases are also being explored. Genetic mapping and comparative analyses help prioritize genomic regions and candidate genes for functional evaluation.','questions':['Which genomic regions are associated with disease resistance?','How can genetic variation guide the selection and validation of resistant germplasm?'],'figs':[(1,'Soybean genome-wide association plot across chromosomes.'),(2,'Genetic relationships among soybean accessions.') ]},
 {'id':'pathogen-genomics','title':'Pathogen Genomics and Effector Identification','tag':'PATHOGEN BIOLOGY','color':'cyan','text':'Field surveillance, pathogen characterization, and genome analysis connect disease pressure with pathogen diversity. We use these complementary perspectives to identify candidate effectors and investigate their roles in plant–pathogen interactions. We are also exploring dsRNA/RNAi-based approaches as targeted tools for next-generation plant disease management.','questions':['How does pathogen diversity relate to disease observed in the field?','Which candidate effectors contribute to interactions with the host?','How can next-generation pathogen-control strategies be further optimized and made accessible for practical disease management?'],'figs':[(3,'South Dakota soybean disease survey coverage map.'),(4,'Soybean plants evaluated under greenhouse conditions.'),('dsrna','Fluorescently labeled synthesized dsRNA attachment assay on Sclerotinia sclerotiorum mycelia.')]},
 {'id':'nlr-temperature','title':'NLR Temperature Sensitivity in Small Grains','tag':'NLR REGULATION IN PLANTS','color':'gold','text':'We study how temperature influences the function of NLR immune receptors in cereal crops. Connecting environmental conditions with resistance phenotypes helps us investigate why immune protection is maintained or weakened across temperature regimes. AI-guided prediction and modeling of temperature-sensitive motifs can help identify structural features associated with temperature-dependent immune function and guide experimentally testable changes in receptor structure.','questions':['How does temperature change NLR-mediated immunity?','Which molecular features support resistance under changing temperatures?','How can protein modeling guide testable designs for temperature-adapted immunity?'],'figs':[(5,'Cereal leaf phenotypes and associated measurements across temperature conditions.')]},
 {'id':'nlr-domain-evolution','title':'NLR Domain Evolution in Grasses and Legumes','tag':'NLR DOMAIN EVOLUTION','color':'violet','text':'We examine how immune receptor domains evolve across grasses and legumes and how that diversity relates to function.','questions':['How has domain diversity shaped immune receptor function?'],'figs':[(6,'Fluorescence microscopy of fungal structures interacting with host cells.'),('rpg5','Conceptual model of the Rpg5 NLR-ID immune receptor.')]},
 {'id':'spatial-regulation','title':'Spatial Regulation of Plant Resistance Expression Circuit','tag':'FUNCTIONAL & SPATIAL GENOMICS','color':'cyan','text':'Resistance responses unfold in particular tissues and at particular times. We integrate tissue imaging and spatial transcriptomics to connect gene expression with biological context and identify expression patterns for functional investigation.','questions':['Where are resistance-associated expression programs active?','How do tissue organization and gene expression change during plant–pathogen interaction?'],'figs':[(7,'Microscopy of sectioned wheat grain tissue.'),(8,'Annotated wheat grain tissue regions with spatial measurements.'),(9,'Spatial genomics analysis panels.') ]},
 {'id':'soil-microbial-genomics','title':'Soil Microbial Genomics','tag':'SOIL MICROBIOME & BIOPRODUCTS','color':'mint','text':'We investigate soil microbial composition and genomic potential to understand how communities relate to plant health. Sequencing and functional analysis help connect microbial diversity with nutrient use and disease suppression.','questions':['Which microbial communities and functions are associated with plant health?','How can genomic information guide the selection of beneficial microorganisms?'],'figs':[(10,'Sequencing output across soil microbial samples.')]},
 {'id':'biostimulants','title':'Biostimulants and Biocontrol','tag':'CORN · SOYBEAN · WHEAT','color':'gold','text':'We evaluate beneficial microorganisms and their products for applications in crop health. Laboratory assays, plant experiments, and local industry partnerships help develop and assess formulations aligned with farmer needs.','questions':['Which locally adapted microorganisms show beneficial activity?','How can promising biological activity translate into practical crop health formulations?'],'figs':[('biostimulant-cultures','Microbial culture assay plates arranged against a dark background.'),('soil-corn-concept','Supplied conceptual figure showing soil microbiome and corn health, research approaches, and intended outcomes.'),('fungal-culture','Fungal colony growing on agar in a Petri dish.'),('culture-comparison','Five microbial culture plates with different colony growth patterns.')]}
]
contents='<nav class="section-index" aria-label="Research theme index">'+''.join(f'<a href="#{p["id"]}"><span>0{i+1}</span>{p["title"]}</a>' for i,p in enumerate(programs))+'</nav>'
research=intro('RESEARCH / SOLANKI LAB','From genes to<br><em>crop resilience.</em>','Integrated research components in the lab connect plant immunity, pathogen biology, functional genomics, and soil microbial solutions to achieve integrative plant health in agricultural systems.')+f'<div class="wrap research-layout"><aside class="program-sidebar"><p class="eyebrow">EXPLORE RESEARCH THEMES</p>{contents}</aside><div class="programs">'
for i,p in enumerate(programs):
    research+=f'<section id="{p["id"]}" class="program accent-{p["color"]}"><p class="eyebrow">0{i+1} / {p["tag"]}</p><h2>{p["title"]}</h2><p class="program-copy">{scientific_text(p["text"])}</p><div class="question-block"><h3>Questions we ask</h3><ul>'+''.join(f'<li>{scientific_text(q)}</li>' for q in p['questions'])+'</ul></div><div class="figure-grid '+('single' if len(p['figs'])==1 or p['id']=='nlr-domain-evolution' else '')+'">'+''.join(figure(n,alt,caption=None if p['id']=='biostimulants' else '',cls='wide' if n==9 or n=='rpg5' else '') for n,alt in p['figs'])+'</div></section>'
research+='</div></div>'
page('research.html','Research','Explore Solanki Lab research themes in disease resistance, NLR regulation, spatial genomics, soil microbiomes, and biological crop health solutions.',research,'Research')

students=[
 ('Sachin Sharma','sachin.sharma@sdstate.edu',15,'Sachin’s research focuses on soybean genomics and major soilborne pathogens, particularly white mold and Fusarium diseases. His work aims to understand host–pathogen interactions and identify genomic factors that contribute to soybean disease resistance.'),
 ('Nikhil','nikhil.lnu@sdstate.edu',16,'Nikhil’s research focuses on the soil microbiome and its practical applications, particularly the discovery of beneficial microbial strains with biostimulant and disease-suppressive potential. His work aims to translate these discoveries into new microbial products for farmers.'),
 ('Israel Akinlabi','israel.akinlabi@sdstate.edu',17,'Israel’s research focuses on the evolution of NLR immune receptors, particularly how they acquire additional integrated domains (NLR-IDs). His work examines how these domains contribute to pathogen recognition, specificity, and immune response in the Rpg5 NLR-ID-mediated immune system in barley.'),
 ('Mrinmoy Sarker','Mrinmoy.Sarker@sdstate.edu','mrinmoy-sarker','Mrinmoy’s research focuses on identifying temperature-sensitive motifs in cereal immune receptors and understanding their role in plant defense. His work particularly examines the RMRL-mediated immune system in barley and wheat and how temperature influences innate immune responses.'),
 ('Chase Tucker','chase.tucker@sdstate.edu',None,'Chase’s research focuses on Cercospora and other foliar diseases of soybean, along with the evaluation of soybean germplasm for disease response.'),
 ('Sonam Rathore','Sonam.Rathore@sdstate.edu',None,'Sonam is an incoming graduate student whose research will focus on dsRNA-based approaches for plant disease control, with particular emphasis on soybean soilborne diseases. Her work will explore targeted RNA-based strategies for managing important soybean pathogens and improving disease resistance.')
]
studenthtml=''
for name,email,n,bio in students:
    slug=name.lower().replace(' ','-');initials=''.join(part[0] for part in name.split())
    note='' if name in ('Chase Tucker','Sonam Rathore') else '<small>Portrait forthcoming</small>'
    alt='Mrinmoy Sarker examining cereal plants in the greenhouse' if n=='mrinmoy-sarker' else name
    portrait=photo(n,alt,'portrait') if n else f'<div class="portrait portrait-placeholder" role="img" aria-label="{name} initials; portrait not supplied"><span>{initials}</span>{note}</div>'
    role='INCOMING GRADUATE STUDENT' if name=='Sonam Rathore' else 'GRADUATE STUDENT'
    studenthtml+=f'<article class="person" id="{slug}">{portrait}<div class="person-copy"><p class="eyebrow">{role}</p><h3>{name}</h3><a class="email" href="mailto:{email}">{email}</a><details class="bio"><summary>Research Bio <span aria-hidden="true">+</span></summary><p>{scientific_text(bio)}</p></details></div></article>'
flags=''.join(f'<span class="country"><img src="assets/brand/{code}.svg" width="24" height="16" alt="">{name}</span>' for code,name in [('us','USA'),('in','India'),('ng','Nigeria'),('bd','Bangladesh'),('pk','Pakistan')])
team=intro('ABOUT THE TEAM','People behind<br><em>the discovery.</em>','A laboratory built on open communication, independent scientific thinking, and shared learning.')+f'''<div class="wrap"><figure class="group-portrait">{photo('group-team','Solanki Lab group together in a meeting room',eager=True)}<figcaption>Solanki Lab · South Dakota State University</figcaption></figure><div class="team-topline"><div><h2>Current Lab Members</h2><div class="countries" aria-label="Nationalities represented across the laboratory">{flags}</div></div><a class="email" href="mailto:SDSUfg-pmsi@jackssdstate.onmicrosoft.com">Contact the lab group ↗</a></div>
<section id="principal-investigator" class="pi-section"><div class="pi-portrait">{photo('shyam-solanki','Shyam Solanki, Principal Investigator')}</div><div><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h2>Shyam Solanki</h2><p class="position">Assistant Professor · Plant Pathology · Functional Genomics<br>Functional Genomics of Plant–Microbe–Soil Interaction</p><p>I am an Assistant Professor at South Dakota State University, where I lead research focused on plant–microbe–soil interactions. My research integrates plant immunity, functional genomics, pathogen biology, and beneficial microbiomes to understand and improve crop resilience. I teach “Field Crop Diseases and Management” (PS 433/533, every spring semester) and “Functional Genomics: EVO MPMI” (700 level, alternate spring semesters).</p><a class="email" href="mailto:shyam.solanki@sdstate.edu">shyam.solanki@sdstate.edu</a><div class="profile-links"><a href="https://www.sdstate.edu/directory/shyam-solanki" target="_blank" rel="noopener">SDSU profile &amp; bio ↗</a><a href="https://scholar.google.com/citations?user=WGHcvhcAAAAJ&amp;hl=en" target="_blank" rel="noopener">Google Scholar ↗</a></div></div></section>
<section id="graduate-students" class="team-section"><p class="eyebrow">OUR TEAM</p><h2>Graduate Students</h2><div class="people-grid">{studenthtml}</div></section>
<section id="undergraduate-students" class="team-section compact-team"><h2>Undergraduate Students</h2><div class="people-grid"><article class="person" id="arsalan-quresh">{photo('arsalan-quresh','Arsalan Quresh in an agricultural field','portrait')}<div class="person-copy"><p class="eyebrow">UNDERGRADUATE STUDENT</p><h3>Arsalan Quresh</h3></div></article></div></section>
<section id="temporary-staff" class="team-section compact-team"><h2>Temporary Staff</h2><div class="simple-person"><h3>Brian Kontz</h3><p>Temporary staff</p></div></section>
<section id="lab-alumni" class="team-section compact-team"><h2>Lab Alumni</h2><div class="simple-person"><h3>Riya Jain</h3><p>Currently a PhD student at Virginia Tech.</p></div></section></div>'''
page('team.html','About the Team','Meet the Solanki Lab team, graduate students, staff, and alumni at South Dakota State University.',team,'About the Team')

outreach=intro('OUTREACH & ENGAGEMENT','Science grows<br><em>through connection.</em>','Genomics education, field engagement, and industry partnerships connect molecular discovery with communities and crop health.')+'''<div class="wrap"><nav class="pill-nav" aria-label="Outreach sections"><a href="#gen-ng">GeN-G &amp; BRING</a><a href="#field-contact">Field Contact</a><a href="#industry">Industry Partnerships</a></nav>'''
outreach+=f'''<section id="gen-ng" class="outreach-section"><div class="split-heading"><div><p class="eyebrow">01 / GENOMICS EDUCATION</p><h2>GeN-G<br><em>Genomics for NewGen</em></h2></div><div><p>A hands-on outreach program introducing students to genomics, DNA sequencing, and plant health through interactive activities, including the Brickopore LEGO DNA sequencer. Developed in collaboration with Dr. Richard Leggett, Earlham Institute, UK.</p><a class="text-link" href="https://brickopore.co.uk/" target="_blank" rel="noopener">Explore Brickopore ↗</a></div></div><div class="outreach-gallery">{figure(19,'Hands-on learning with plants in the laboratory.')}{figure(20,'Demonstrating the Brickopore LEGO DNA sequencer.')}{figure(21,'Lab members together during a laboratory visit.')}{figure(22,'GeN-G Genomics for NewGen outreach poster.')}</div><div class="bring-note" id="gen-ng-bring"><p class="eyebrow">EXPANDING ACCESS</p><h3>GeN-G BRING</h3><p>Our GeN-G BRING program expands hands-on genomics education to rural and Native communities, connecting students with sequencing, plant science, and emerging technologies while strengthening links between communities and research institutions.</p></div></section>
<section id="field-contact" class="outreach-section"><div class="split-heading"><div><p class="eyebrow">02 / FIELD CONTACT</p><h2>Across South Dakota.</h2></div><p>Our field outreach focuses on soybean disease surveys, corn microbiome research, and crop health across South Dakota. We regularly visit fields, collect samples, and meet directly with farmers and stakeholders across the state to connect laboratory research with real-world production challenges.</p></div><div class="field-gallery">{figure(23,'Participants at a soybean research symposium.')}{figure(24,'Field discussion and examination of crop samples.','Still image from a field video.')}{figure(25,'Close-up views of soybean stem symptoms.')}{figure('field-outreach','Lab members discussing plant health research with visitors at an outreach display.',caption=None)}</div></section>
<section id="industry" class="outreach-section industry-section"><p class="eyebrow">03 / INDUSTRY PARTNERSHIPS</p><h2>Solutions shaped<br>by farmer needs.</h2><p>We work with local industry partners to develop practical formulations aligned with farmer needs, particularly from our research in microbiome genomics, biostimulants, and biological control. The goal is to translate laboratory discoveries into field-ready crop health solutions.</p><a class="text-link" href="research.html#biostimulants">Explore biostimulants and biocontrol ↗</a></section></div>'''
page('outreach.html','Outreach & Engagement','GeN-G and GeN-G BRING genomics outreach, South Dakota field contact, and local industry partnerships.',outreach,'Outreach')

funding='''<section class="page-intro wrap funding-summary"><p class="eyebrow">RESEARCH SUPPORT</p><h1>Funding</h1><p class="page-lead">Our integrated research is supported through a combination of federal competitive funding and commodity-group competitive funding. The Solanki Lab is currently supported through <span id="federal">programs from the National Science Foundation (NSF), U.S. Department of Agriculture (USDA)</span>, and <span id="commodity">commodity groups supporting corn, soybean, and wheat research</span>. This support enables our research while providing opportunities for graduate and undergraduate students to participate in discovery and training. We gratefully acknowledge all organizations and stakeholders who support our work.</p><p class="funding-keyline">NSF · USDA · Corn · Soybean · Wheat · Research and Student Training</p></section>'''
page('funding.html','Funding','Federal and commodity-group support for Solanki Lab research and student training: NSF, USDA, corn, soybean, and wheat.',funding,'Funding')

recruitment=intro('JOIN THE LAB','Recruitment','We welcome inquiries from prospective graduate students, postdoctoral researchers, and visiting researchers whose interests align with the research directions of the Solanki Lab.')
recruitment+='''<div class="wrap recruitment-content"><p class="recruitment-keyline">Fellowships · Grant-Funded Positions · <a href="mailto:shyam.solanki@sdstate.edu">Contact the Lab</a></p><section id="fellowships" class="recruitment-section"><h2>Fellowship-Supported Opportunities</h2><p>Prospective graduate students and postdoctoral researchers are encouraged to pursue competitive fellowship opportunities, including programs such as the NSF Graduate Research Fellowship Program (GRFP) and relevant USDA predoctoral and postdoctoral fellowships. If you are interested in joining the lab through a fellowship, please reach out to me. I would be happy to discuss potential research directions and help develop a competitive fellowship application that aligns with the lab’s research program.</p></section><section id="funded-positions" class="recruitment-section"><h2>Funded Positions</h2><p>Most graduate students and research trainees in my lab are supported through grant-funded positions that I receive from federal agencies, commodity groups, and other competitive funding programs. Because these opportunities depend on current and newly awarded research grants, funded positions are not continuously available and may open only when new support becomes available.</p><p>When I have an opening, I will post the position in the Recruitment section and on social media platforms. If you are interested in joining the lab, please email <a class="email" href="mailto:shyam.solanki@sdstate.edu">shyam.solanki@sdstate.edu</a> with a brief description of your research interests, relevant academic or research experience, and how your background aligns with the lab’s research program. I receive many inquiries and may not be able to respond to every message; however, every relevant application receives full consideration. I will contact applicants whose background and research interests align with an available or anticipated position.</p></section></div>'''
page('recruitment.html','Recruitment','Fellowship-supported opportunities, grant-funded positions, and inquiries about joining the Solanki Lab at South Dakota State University.',recruitment,'Recruitment')

guidelines=build_guidelines()
page('guidelines.html','Lab Guidelines','Read the complete Solanki Lab FG-PMSI guidelines, including research expectations, equipment, and HPC data storage and transfer.',guidelines,'Lab Guidelines',extra_head='<link rel="stylesheet" href="guidelines.css?v6-20260907">')
print('Built homepage and six dedicated pages.')
